### ISSUE TITLE
Spike: Check 3 (or more) ways to autoscale cluster

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1121]
Verify and check the following possibilities for autoscaling Kubernetes cluster: 
1. using Virtual Kubelet
2. using Prometheus metrics + Alartmanager and Epiphany svc that handles the request to scale up/down 
3. using Autoscaling Controller for Kubernetes that triggers provisioning/deleting node. 
4. You name it!

**Comment by sk4zuzu** [comment]
Results from the research:

> 1. using Virtual Kubelet

This is a nice concept for cloud Epiphany as an option/addition. Unfortunately, it would not work well on-premise (would for example require a custom nomad cluster or something similar - depending on available providers) so we decided to drop it. Also for example AWS provider project for VK seems to be stale https://github.com/virtual-kubelet/aws-fargate. 

> 2. using Prometheus metrics + Alartmanager and Epiphany svc that handles the request to scale up/down

This is the path that we have chosen. These are the steps we identified https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/autoscaling/autoscaling.md. Here's unfinished code from the PHASE1 in the doc https://github.com/sk4zuzu/epiphany/commit/031d6e7a2aa67993e2f48765d810ffa95cff7321 (implementation has been stopped).

> 3. using Autoscaling Controller for Kubernetes that triggers provisioning/deleting node.

I looked at this and I think this is a correct path (at least for the cloud), but because of the on-premise requirement point 2. is the favourite one.

> 4. You name it!

Nothing here. :(

__Considering the requirement that we have to support cloud and on-premise simultaneously__, point 2. from the above list seems to be the only option.
