### ISSUE TITLE
Create TLS/SSL cert manager service

### ISSUE THREAD

**Issue by baurbaniak** [epiphany-platform/epiphany#1232]

**Comment by plirglo** [comment]
Cert-manager might be deployed from standard manifest fire or from Helm chart (Since we've got Helm we should consider second option)

- [kubernetes documentation](https://cert-manager.io/docs/installation/kubernetes/) 
- [interesting Medium introduction](https://itnext.io/automated-tls-with-cert-manager-and-letsencrypt-for-kubernetes-7daaa5e0cae4)

**Comment by mkyc** [comment]
What would be use case? Do we agree that we would need DNS records available to automation?

**Comment by seriva** [comment]
Closing for now as we don't have a business case for this.
