### ISSUE TITLE
EKS cluster epiphany configuration

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1445]
Create EKS cluster configuration to be able to create it using epiphany. 

**Is your feature request related to a problem? Please describe.**
We need to have possibility to create EKS cluster with epiphany. 

**Describe the solution you'd like**
In previous tasks in order (#1442, #1443) terraform scripts should already be prepared. That means that here we want to develop yaml configs similar to what we have in epicli, inserting those previously prepared terraform scripts, embed it in epiphany environment to be able to create cluster with epiphany. This task is basically "do the thing" task. Previous ones are preparations.

**Describe alternatives you've considered**
This task has to consider what would be output from task #1462 as it will discuss modularisation in epiphany. 

**Additional context**
No.

**Comment by przemyslavic** [comment]
The purpose of this task is to prepare yaml configuration files to be able to create EKS cluster with Epiphany.
This task strictly depends on the results of research on the component versioning epic https://github.com/epiphany-platform/epiphany/issues/1463 so that Epiphany would be more modular and easier to use and maintain.

**Comment by mkyc** [comment]
As is was decided we are not going to include any managed kubernetes clusters configuration inside epiphany, but we will release EKS as separate module. Work defined in #1636
