### ISSUE TITLE
[Spike]Research Rook Operator version upgrade process

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1450]
**Is your feature request related to a problem? Please describe.**
We don't have any possibility to upgrade ceph claster from one version to another and we don't have any documentation about it and related to that.

**Describe the solution you'd like**
We want to install rook operator / ceph cluster in version A and upgrade it to version B using epiphany platform. Also we want to check how is process being handled and security of this solution and create documentation of that.

**Describe alternatives you've considered**
No alternative.

**Additional context**
We should based on the official documentation with upgrade instruction: https://rook.io/docs/rook/v1.3/ceph-upgrade.html

**Comment by rpudlowski93** [comment]
Rook Ceph upgrade can be done very easily using official documentation : https://rook.io/docs/rook/v1.4/ceph-upgrade.html
Be aware that upgrade for each version could be slightly different. In case of upgrade rook ceph (operator and cluster) from version 1.3 to version 1.4 it is enough to run the following commands but before it, please make sure that Your cluster and operator are in [healthy status](https://github.com/rook/rook/blob/master/Documentation/ceph-upgrade.md#health-verification): 

1. Update the RBAC and CRDs
```
kubectl delete -f upgrade-from-v1.3-delete.yaml
kubectl apply -f upgrade-from-v1.3-apply.yaml -f upgrade-from-v1.3-crds.yaml 
```
2.Update the Rook Operator - If operator is updated, all ceph daemons will be updated as well.
```
kubectl -n rook-ceph set image deploy/rook-ceph-operator rook-ceph-operator=rook/ceph:v1.4.1
```


After that, Your can  check Your upgrade status: 
```
watch --exec kubectl -n rook-ceph get deployments -l rook_cluster=rook-ceph -o jsonpath='{range .items[*]}{.metadata.name}{"  \treq/upd/avl: "}{.spec.replicas}{"/"}{.status.updatedReplicas}{"/"}{.status.readyReplicas}{"  \trook-version="}{.metadata.labels.rook-version}{"\n"}{end}
```

Cluster storage shoudn't have downtime since all the daemons pods will be updated 1 by 1 (for example OSD and MON pods use rolling updates strategy), so the upgrade doesn't affect on Your application uptime which should be available all the time.

Thanks to @mkyc it is easy to check and create rook ceph cluster in version 1.3 and upgrade it automatically to version 1.4, using the ready-to-use scripts: https://github.com/mkyc/k8s-rook-ceph. Now, we should implement the upgrade process from this repo to epiphany.

**Comment by mkyc** [comment]
As there is no separate PR in this task, I will push it to next phase.
