### ISSUE TITLE
[spike] EKS on different operating systems

### ISSUE THREAD

**Issue by ghost** [epiphany-platform/epiphany#1512]
**Is your feature request related to a problem? Please describe.**
In Epiphany we used different operating systems do preform complete deployment of kubernetes cluster. EKS and terraform repo comes with Amazon Linux 2 by default. Currently I don't see any options to use it in terraform scripts - still looking for a solution. 

**Describe the solution you'd like**
More research required.

**Describe alternatives you've considered**
_Amazon Linux_ offers deployments of 1.17 -  his is an option, which needs to be tested in our scenario.
_Ubuntu_ - its possible to setup kubernetes in version 1.16 only (needs to be tested)
- https://docs.aws.amazon.com/eks/latest/userguide/eks-partner-amis.html 

**Additional context**
N/A

**Comment by mum0l** [comment]
It is possible to deploy **Ubuntu** EC2 instances with EKS, but only with kubernetes 1.16 and autoscaler 1.16. Tested and works properly. Full list of available Ubuntu images can be found under following url: https://cloud-images.ubuntu.com/aws-eks/

**Comment by mum0l** [comment]
Still working on RedHat EC2 machine preparation.
So far, after adjusting and building an RH image, and deployment, it hangs on _coredns_, and no nodes are available via kubectl.

**Comment by mum0l** [comment]
By default, EKS installs the official fully supported and maintained image of Amazon Linux 2. In this ticket we want to setup RedHat or Ubuntu, as a worker for K8S.

So far it’s only possible to deploy k8s v1.16 max using official Ubuntu image, but we need also 1.17 which doesn't exist.. 

Regarding RedHat, it’s required to build own image, and customize it. I start working on that, but looks like topic is quite huge, and I see no logic reason, why we need to use it.. Preparing this image cost a bit of time, but later on, we need to provide support for it, so it will be another toy to carry about.. Taking above into account, I suppose we need to skip this idea, as it doesn’t make sense for us (mainly because of the future image maintenance)..

**Comment by rpudlowski93** [comment]
In AKS case the situation is a bit similar, there is only option to have Linux (Ubuntu) and Windows, nothing more. I would prefere to stick the images which Azure/AWS offer by default. I can approve using only Amazon Linux 2 in this case.

**Comment by seriva** [comment]
Closing as we currently don't have a valid business case anymore.
