### ISSUE TITLE
[FEATURE REQUEST] Prepare EKS module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1636]
After the https://github.com/epiphany-platform/epiphany/issues/1637 AWS Basic Infrastructure module is ready we can start working on deploying EKS on top of it. It should have similar structure to the AKS Module.

We need to do:
* create new git repo for the module
* implement required methods, for starters: Metadata, Init, Plan, Apply, Audit.
* Tests will be implemented in #1676 and #1677

Existing set of makefiles from https://github.com/epiphany-platform/epiphany/tree/develop/docs/design-docs/modular-cli/cpt-tests can be used as a template.
Here is an example of a working module https://github.com/seriva/component-cli

**Comment by mkyc** [comment]
@sk4zuzu would you add some comment on that? I believe we tested it, so maybe we can move it further?

**Comment by sk4zuzu** [comment]
Yes initial test showed problems with internet connectivity in vms. It was later fixed in those PRs https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/12 and https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/17.
I have seen issues with destroying EKS resources, but we'll deal with it in specific issues later.
So IMO for now it's all OK we can move forward. :+1::innocent:

**Comment by atsikham** [comment]
@sk4zuzu But the issue with internet connectivity was not in this module. I've also seen some issues there, one is described in readme, and hopefully we will not have such issues when get rid of [used](https://github.com/terraform-aws-modules/terraform-aws-eks) terraform module.
