### ISSUE TITLE
Pipeline to test AwsKS module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1643]
**Is your feature request related to a problem? Please describe.**
Create pipeline to run tests on PR merge
**Describe the solution you'd like**
Pipeline should invoke tests prepared in #1677
**Describe alternatives you've considered**
No.
**Additional context**
Check #1641 for information how t was done for AZBI module.

**Comment by ar3ndt** [comment]
dummy [PR](https://github.com/epiphany-platform/m-aws-kubernetes-service/pull/34)

**Comment by ar3ndt** [comment]
[PR](https://github.com/epiphany-platform/m-aws-kubernetes-service/pull/34)

**Comment by atsikham** [comment]
Checked that pipeline works, tests run, image is pushed to Azure registry (at the moment of testing the latest image version is 0.0.1.4892).
Notes:
* Pipeline is moved to yaml-pipelines dir in Azure
* AWSBI image tag is set explicitly in pipeline ENV variables to `epiphanyregistry.azurecr.io/epiphanyplatform/awsbi:0.0.1.4701`
* 85.71% tests are passed, as "apply" test is skipped because of the [issue](https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/32)
