### ISSUE TITLE
[FEATURE REQUEST] Run Helm tasks from Epiphany container

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1656]
**Is your feature request related to a problem? Please describe.**
In #1638 it was decided not to wrap `kubectl` to execute locally and example provided how to change configuration in #1639. 
This task requires investigation what needs to be changed for helm part of that work.

**Describe the solution you'd like**
 Investigate and apply what needs to be changed for helm part of execution in the local container.

**Describe alternatives you've considered**
No.

**Additional context**
See [example](https://github.com/epiphany-platform/epiphany/pull/1655).

**Comment by seriva** [comment]
Using helm locally to deploy charts to a K8s cluster can be done with the changes already made for #1616:

- Local kube.conf which points to localhost:6443
- Setting of KUBECONF env variable to point to that local kube.conf
- SSH tunnel passing through port 6443 to our K8s master

Only thing missing is adding our own Helm repository which we can do by using the same SSH tunnel trick we use for local kubectl:

- SSH tunnel passing through port 80 to our repository machine
- Add the repository using localhost address instead of the normal IP
- deploy charts like normal.

**Comment by przemyslavic** [comment]
It has been tested together with the task [[FEATURE REQUEST] update network security rule to open port 6443 #1616](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/1616).
