### ISSUE TITLE
decide if build and test processes of modules should be OS independent

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1700]
> > Hmmm ... I didn't consider that we are going to run that on Windows to be fair, but that is good point.
> 
> If we are not going to do so, we can just leave a note about that.

It has to be a new issue/spike how we should deal with it.

_Originally posted by @rafzei in https://github.com/epiphany-platform/m-aws-basic-infrastructure/pull/1#issuecomment-698857681_

**Comment by mkyc** [comment]
We might run build / test / whatever [inside docker container](https://itnext.io/docker-in-docker-521958d34efd).

**Comment by mkyc** [comment]
We should also have a look at [this](https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/17) PR from @seriva if it solves OS problems.

**Comment by seriva** [comment]
After a bit of research I think that we should **NOT** try and make testing/developing the modules OS independent. Linux and Mac should work fine and on Windows there are some easy ways to work around the issues.

For development I think we should add a VSCode devcontainer to every module (Already added to 3 of 5 we have now). This is not only useful on Windows but can also aid during development on MacOS and Linux:
    -  Dependencies like terraform, azure-cli etc are always the right version when developing. No need to switch when working on different modules.
    - No need to rebuild the container every time to test/run something
    - Nice plugins for VSCode for various things like bash, python, terraform or whatever the module uses.

If there is a need to build the module container because there is a need to check interactions between modules etc, Linux and MacOS should work fine and onn Windows WSL(2) can be used:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

In WSL2 you can easily share the docker host between Windows and the WSL2 environment by using the WSL2 backend:

![image.png](https://images.zenhubusercontent.com/5efee199ee690405efd9d38b/f6082fb4-6b47-4283-8ea3-87cd3a9a8d65)
![image.png](https://images.zenhubusercontent.com/5efee199ee690405efd9d38b/b9ed2246-ce43-4310-9d7e-478f90dc2c81)

In WSL1 you can achieve the same with this tutorial:

https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly
![image.png](https://images.zenhubusercontent.com/5efee199ee690405efd9d38b/649ea4a9-cf6f-4328-99f6-6ac581a1fb90)

Finally for working with WSL VSCode also has some plugin to make the development seamless:

**Comment by mkyc** [comment]
@atsikham can you validate what @seriva wrote? Some comment how you configured your environment would be also helpful.

**Comment by atsikham** [comment]
@mkyc to use WSL2, every time I switch to the laptop that supports it. It took a long time with WSL1, so I decided not to proceed with that (finally it started to launch, but then issues with docker volumes started occur). Example of issue I met on WSL1: https://github.com/microsoft/WSL/issues/5125. In general, working on Windows with modules is possible, but for me it's not convenient.

**Comment by atsikham** [comment]
Will we move this task forward?

**Comment by mkyc** [comment]
Yeah, I believe everyone who is interested already got familiar with this.
