### ISSUE TITLE
[BUG] Upgrade elasticsearch-oss to 7.9.1 & ODFE to the latest version (1.10.1)

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1719]
**Describe the bug**
During testing I found [this regression bug in Elasticsearch v7.8.0](https://github.com/elastic/kibana/issues/69545). It was fixed in ES 7.8.1, see [PR](https://github.com/elastic/elasticsearch/pull/58418).

**To Reproduce**
It's not possible to upgrade only Elasticsearch without Open Distro for Elasticsearch, for example:

```
apt-get install opendistro-alerting
The following packages have unmet dependencies:\n opendistro-alerting : Depends: elasticsearch-oss (= 7.8.0) but 7.8.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
**Expected behavior**
Successful installation. 

**Config files**
No.

**OS (please complete the following information):**
 - OS: All

**Cloud Environment (please complete the following information):**
 - Cloud Provider: All

**Additional context**
ODFE just released new version (1.10.1), see [here](https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/376).

_Originally posted by @to-bar in https://github.com/epiphany-platform/epiphany/issues/1140#issuecomment-702062434_

**Comment by mkyc** [comment]
This task fixes issue introduced in #1140

**Comment by rafzei** [comment]
On block because of https://github.com/epiphany-platform/epiphany/issues/1741

**Comment by to-bar** [comment]
With PR #1718 we have introduced Jinja template for jvm.options file. This file defines JVM heap size (`Xmx`). The default is 1 GB but Elasticsearch doc says:

> When moving to production, it is important to configure heap size to ensure that Elasticsearch has enough heap available.

So it is very likely that one could increase the JVM heap size. But for `epicli upgrade` we do not support defining custom values for new configuration settings. The setting `specification.jvm_options` has been introduced in v0.8.0rc1.
Current code (for upgrades) always uses the default value, i.e 1 GB (see PR #1763), so **any customized value is overwritten during the upgrade**. To solve this issue we can try to get the existing setting from remote host (from jvm.options file) to preserve the custom value instead of overwriting it with the default.

More info: https://www.elastic.co/guide/en/elasticsearch/reference/7.9/heap-size.html

This JVM heap size issue can be solved in separate PR.

**Comment by rafzei** [comment]
@przemyslavic @to-bar Was it tested? If so, please move it to the correct column.

**Comment by przemyslavic** [comment]
Tested mainly by @to-bar.
