### ISSUE TITLE
[UPGRADE] Upgrade Docker to v19.03.14

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1855]
**Is your feature request related to a problem? Please describe.**
- Docker-ce 18.09.9 end of support (11.2020)
- [CVE-2019-5736 & CVE-2019-13139 & CVE-2019-16884 & CVE-2019-13509](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Adocker&cpe_product=cpe%3A%2F%3Adocker%3Adocker&cpe_version=cpe%3A%2F%3Adocker%3Adocker%3A18.09.0)

**Describe the solution you'd like**
- upgrade to the latest version if possible
- backport to supported Epiphany versions

**Comment by sk4zuzu** [comment]
I believe we should upgrade docker only to versions supported by Kubernetes cluster at hand and not newer.

**Comment by to-bar** [comment]
The source of true for validated Docker version is:
https://github.com/kubernetes/kubernetes/blob/release-1.18/vendor/k8s.io/system-validators/validators/docker_validator.go
```
const (
	dockerConfigPrefix           = "DOCKER_"
	latestValidatedDockerVersion = "19.03"
)
```
19.03 is validated since 1.17, see [PR](https://github.com/kubernetes/kubernetes/pull/84476).

Backporting this issue we can also [try to use 19.03](https://github.com/kubernetes/kubernetes/issues/82326#issuecomment-548769247):

> the usage of Docker 19.* is not blocked in any way in 1.16.
> you can ignore the WARNING SystemVerification and just use it.

**Comment by przemyslavic** [comment]
Tested automatically in the pipeline with @to-bar.
✔️ `epicli apply`
✔️ `epicli upgrade` from 0.4.x, 0.5.x, 0.6.x, 0.7.x, 0.8.x to develop
