### ISSUE TITLE
[FEATURE REQUEST] Upgrade skopeo to v1.2.0 or newer

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1877]
**Is your feature request related to a problem? Please describe.**
We use skopeo v0.1.40-dev and occasionally get network related errors such as `Invalid status code returned when fetching blob 502 (Bad Gateway)`. We do not have retry functionality so deployment fails.

The latest skopeo supports [retries on commands](https://github.com/containers/skopeo/issues/918) and includes many [improvements](https://github.com/containers/skopeo/releases).

**Describe the solution you'd like**
Upgrade skopeo version used by Epiphany.

**Additional context**
n/a

**Comment by seriva** [comment]
Closing this issue as a new issue was created for replacing Skopeo with Crane here: #2081.

In short, newer versions of Skopeo present the following issues:

1. No support for universal Go binaries anymore. Each OS would need to have each own build version we need to ship instead of the single multi OS binary we use now.
2. With the additional requirement to support ARM we need to be able to download images from ARM based systems. However the ARM support on Skopeo is sketchy and the builds for that are not straightforward.
3. Skopeo does not provide easy to use binaries anymore. Only through the package managers from various OS`s. This however is not ideal on how we need to deliver it to customers.
