### ISSUE TITLE
[SPIKE] Check available solutions for providing/deploying Kafka

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1976]
**Is your feature request related to a problem? Please describe.**
Right now we are installing kafka directly from tar.gz file and perform its configuration.

**Describe the solution you'd like**
Do research on available Kafka installer and compare them. Opensource solutions managed 'outside' are preferred, but also we want to provide guidance when to choose commercial solution, because of potential requirements.

**Describe alternatives you've considered**
Maybe some commercial soft?

**Comment by mkyc** [comment]
Regarding Kafka on Kubernetes I noticed once [this article](https://blog.usejournal.com/kafka-on-kubernetes-a-good-fit-95251da55837). It's almost 2 years old, but I believe that it still provides some good base to start our own research.

**Comment by atsikham** [comment]
My thoughts for now:

* We cannot start with the Kafka module while we don't know about offline/upgrade parts - this is important as we will implement that. As this spike is only about installation (and I think it's ok as otherwise this task is huge), new tasks have to be created. _For upgrades the ability to work with already installed Kafka has to be checked_.
* It's better to start with offline/upgrade after installation spike, not to do the same work a few times. Also after this spike we can reduce the number of solutions to verify for upgrades and offline mode.
* Upgrade and offline installation spikes can be done in parallel.

**Comment by mkyc** [comment]
I reviewed document in internal location (Epiphany->Development->Spikes/PoCs->Kafka Deployment Options) and it looks good as first review of available options.

**Comment by atsikham** [comment]
I also reviewed the document, LGTM. 
If we choose Strimzi, it's not clear if we are going to integrate it somehow with modules.
