### ISSUE TITLE
ensure final set of requirements

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2031]
**Is your feature request related to a problem? Please describe.**
We need to collect all the requirements for that epic. We currently know following:
 * ARMv8 ARM64
 * components: ELK, Grafana, Prometheus, Kibana, Kafka, K8s, HAProxy, Keycloak (with PostgreSQL)
 * Centos 7
 * provider any (we do not want to provide ARM infrastructure here)

It's required to collect any other requirements soon. 

**Describe the solution you'd like**
Have all requirements here. 

**Describe alternatives you've considered**
No. 

**Additional context**
Unknown.

**Comment by erzetpe** [comment]
- Check system resources available - CPU, RAM, disk - to be able to choose proper solution k8s vs. k3s for example

**Comment by to-bar** [comment]
- Consider newer OS than CentOS 7, for example CentOS 8 would bring:
  - Python 3.6 as the default platform Python instead of Python 2.7 (system tools in CentOS 8 use Python 3.6 provided by the internal `platform-python` package. Red Hat advises customers to use `python36` package instead or newer)
  - Bash 4.4 (4.2 in CentOS 7.9), bash 4.4 brings a lot of improvements, for example: 
    - in bash 4.3 and older it is not possible to obtain the exit code of a process substitution command from the shell that created the process substitution
    - nameref variables
- Start with #2032

**Comment by erzetpe** [comment]
@to-bar The problem with starting right now with CentOS 8 is that it's add another part of uncertainty to totally new field for us. Probably the safer solution even if it has many drawback is do first support on Centos 7 on ARM architecture, to avoid additional issues.

**Comment by to-bar** [comment]
@erzetpe agree that this would increase uncertainty so I opt for doing a spike in order to test whether it is possible to deploy Epiphany cluster on CentOS 8 and if not, what kind of issues we would have.

CentOS 8 was released in 2019 so we are not up to date. IMO before releasing the `extended support` version of Epiphany, we should at least try to abandon RHEL/CentOS 7 for new clusters. The LVM merge task is the first step 😉

**Comment by seriva** [comment]
Additional confirmed information so far:

1. OS: Centos 7

2. Only ```any``` provider needed as they are looking at bare metal hardware.

3. Needed components:
-	Kubernetes, 
-	Kafka
-	HAProxy
-	ELK (Logging)
-	Prometheus + Grafana + Exporters (Monitoring)
-	PostgreSQL
-	Keycloak
-	RabbitMQ

4. Priority of components:
- Kubernetes, Kafka, HAProxy
- KeyCloak + PostgreSQL
- RabbitMQ
- ELK + Prometheus + Grafana + Exporters

5: PostgreSQL is only for KeyCloak and does not require any advanced features like: PGPool, Redmngr etc.

**Comment by mkyc** [comment]
I believe it's good enough for now.
