### ISSUE TITLE
[FEATURE REQUEST] Update Ubuntu 18.04-LTS images to the latest

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2142]
**Is your feature request related to a problem? Please describe.**
Update `Ubuntu 18.04-LTS` images used in the cloud to the latest version before releasing v0.10.0.

Please update Azure DevOps pipelines, documentation and epicli defaults.

**Additional context**

Latest images as for today:
AWS:
`ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20210315.1`

Azure:
` Canonical:UbuntuServer:18.04-LTS:18.04.202103151`

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by przemyslavic** [comment]
Pipelines updated.

**Comment by plirglo** [comment]
Created PR (draft) with changes:
https://github.com/epiphany-platform/epiphany/pull/2152
There is also documentation change.
Since we are changing images between versions the documentation does not say true.
It's not save to re-run apply after upgrade since terraform will destroy machines - we need to invent some fix for this and/or change documentation.
We are in testing process with @przemyslavic to establish the solution for this.
I will move PR to "ready" state after those tests.

**Comment by przemyslavic** [comment]
Images for Ubuntu have been updated and tested. Documentation on extending OS disks has been added.

**Comment by mkyc** [comment]
Even newer images found and applied.
