### ISSUE TITLE
[SPIKE] Leader election for pods

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2232]
Check possibilities to provide a mechanism to pick a k8s pods leader.
Describe the best solution for that and create a new issue to implement it.

If the spike outcome will be that we cannot provide such a universal mechanism for pods, it should be well described why.

**Additional context**
It came from one of the internal teams

More info:
https://kubernetes.io/blog/2016/01/simple-leader-election-with-kubernetes/
https://tunein.engineering/implementing-leader-election-for-kubernetes-pods-2477deef8f13

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by seriva** [comment]
Some references:
https://kubernetes.io/blog/2016/01/simple-leader-election-with-kubernetes/
https://tunein.engineering/implementing-leader-election-for-kubernetes-pods-2477deef8f13
https://carlosbecker.com/posts/k8s-leader-election/

**Comment by rpudlowski93** [comment]
Result of my spike:

Leader election in Kubernetes: components of control plane such as controller manager or scheduler use endpoints to select the leader. Instance which firstly create the endpoint of this service at the very beginning add annotation to the endpoint with the leader.

Package leaderelection.go is used for leader election process which leverages above Kubernetes endpoint resource as some sort of LOCK primitive to prevent any follower to create the same endpoint in this same Namespace.

As far as leader election for pod is considered there are possible a few solutions:

1) Since Kubernetes introduced in 1.14 version (March, 2019) coordination.k8s.io group API, it is possible to create in the cluster lease object which can hold the lock for the sets of pods. It is necessary to implement a simple code into the application using package leaderelection.go in order to handle the leader election mechanism.

Helpful article: 
- https://carlosbecker.com/posts/k8s-leader-election/

This is the recommended solution, simple, based on existing API group and lease object and not dependent on any external cloud object. 

2) Kubernetes already uses Endpoints to represent a replicated set of pods so it is possible to use the same object for the purposes. It is possible to use already existing leader election [framework](https://github.com/kubernetes/contrib/tree/master/election) from Kubernetes which implement simple mechanism. It is necessary to run leader-election container as sidecar container for replication set of application pods. Using the leader-election sidecar container, endpoint will be created which will be responsible for locking leader for one pod. Thanks to that, creating deployment with 3 pods, only one container with application will be in ready state - the one that works inside the pod leader. For application container, it is necessary to add readiness probe to the sidecar container:

Helpful article: 
- https://kubernetes.io/blog/2016/01/simple-leader-election-with-kubernetes/

This solution was recommended by Kubernetes in 2016 and looks a little outdated, it is more complex and require more work.

3) Microsoft and Google come up with a proposal to use cloud native storage with single object that contain the leader data but it require to read that file by each node what can be in some situations problematic. 

Helpful articles: 
- https://cloud.google.com/blog/topics/developers-practitioners/implementing-leader-election-google-cloud-storage
- https://docs.microsoft.com/en-us/azure/architecture/patterns/leader-election

It is not recommended solution since the single object is a potential single point of failure.

Regarding the implementation of this feature into Epiphany, I would suggest to only add the spike result to our documentation because Epiphany team is not responsible for the deployment and application configuration side. Leader-election framework use endpoint object which is the basis of Kubernetes.

**Comment by rpudlowski93** [comment]
Documentation added in PR #2339
