### ISSUE TITLE
[SPIKE] Check compatibility matrix for PostgreSQL related components

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2303]
**Is your feature request related to a problem? Please describe.**
We need to update PostgreSQL related env and before this we need to make research on what is compatible with what.

Components to check (for all supported OS distributions + ARM architecture for CentOS):
- pgAudit
- PgBouncer
- Pgpool (only k8s deployment)
- repmgr

**Describe the solution you'd like**
Compatibility matrix that would allow us to decide to which PostgreSQL version we can upgrade (12 or 13).

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
Because it is a blocker for the rest of the tasks in the current sprint I decided to speed it up a little and put all findings in a comment.

Postgresql publish **Feature Matrix** to see what features are included in particular supported PostgreSQL version, see [here](https://www.postgresql.org/about/featurematrix/)

Postgresql latest release | 13.3 | 12.7 | 11.12
 --- |--- | --- | ---
 Release date | Thursday, May 13, 2021 | Thursday, May 13, 2021 | Thursday, May 13, 2021 
EOL | Thursday, November 13, 2025 | Thursday, November 14, 2024 | Thursday, November 9, 2023 
[pgAudit](https://github.com/pgaudit/pgaudit#postgresql-version-compatibility) (latest)	| [v1.5.x (v1.5.0)](https://github.com/pgaudit/pgaudit/releases/tag/1.5.0) | v1.4.x | v1.3.x 
PgBouncer (latest)| v1.15.x | -	| -	
PgPool (latest) | [v4.2 (v4.2.2)](https://www.pgpool.net/docs/pgpool-II-4.2.2/en/html/example-cluster.html) | - | [v4.1 (v4.1.6)](https://www.pgpool.net/docs/pgpool-II-4.1.6/en/html/example-cluster.html )
[repmgr](https://repmgr.org/docs/5.2/install-requirements.html#INSTALL-COMPATIBILITY-MATRIX) | v5.2 |v5.2 | v5.2

(Yesterday was released Postgresql versions 13.3, 12.7, 11.12, 10.17, and 9.6.22  - fix bunch of issues and CVE's, see [here](https://www.postgresql.org/about/news/postgresql-133-127-1112-1017-and-9622-released-2210/))

 PgPool / PgBouncer don't explicit specify compatibility with particular PostgreSQL versions, they only advise that you should use the latest **stable** version.
 PgPool: "Supported PostgreSQL server's versions are 6.4 and higher. To use the parallel query feature, however, 7.4 and higher must be used."
 However, I found some example configs in official PgPool documentation with PostgreSQL version specified (see links in above table)

 
As described in [ARM documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/ARM.md#components) pgpool and pgbouncer are not supported by Epiphany. I figured out that PgPool actually was released for ARM but its not up to date version.

RHEL7/CentOS7:
RPM name | Release date
 --- |--- 
 postgresql-pgpool-II-3.4.6-1.el7.aarch64.rpm | 2016-10-15
 postgresql-pgpool-II-devel-3.4.6-1.el7.aarch64.rpm | 2016-10-15 
 postgresql-pgpool-II-extensions-3.4.6-1.el7.aarch64.rpm | 2016-10-15
 
 RHEL8/CentOS8: 
 RPM name | Release date
 --- |--- 
pgpool-II-10-4.1.3-1.rhel8.aarch64.rpm | 8/20/2020
pgpool-II-10-4.1.4-1.rhel8.aarch64.rpm | 9/17/2020 

Additional links may be useful:
PgPool [Bitnami image](https://hub.docker.com/r/bitnami/pgpool/tags?page=1&ordering=last_updated)
PgBouncer [Bitnami image](https://hub.docker.com/r/bitnami/pgbouncer/tags)
PostgreSQL [RHEL](https://www.postgresql.org/download/linux/redhat/) & [Ubuntu](https://www.postgresql.org/download/linux/ubuntu/)
PgAudit & PgBouncer also available via above official repository
Repmgr [repos for all distro](https://repmgr.org/docs/5.2/installation-packages.html)

**Comment by rafzei** [comment]
PgBouncer latest version was released for ARM arch: [rpm](https://ftp.postgresql.org/pub/repos/yum/common/redhat/rhel-7-aarch64/pgbouncer-1.15.0-1.rhel7.aarch64.rpm) (thx @atsikham)
