### ISSUE TITLE
[SPIKE] Operating System's upgrade (RHEL8 & Ubuntu20.04)

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2529]
**Is your spike related to a problem or idea? Please describe.**
We have to support RHEL8 and Ubuntu 20.04.

**Describe the outcome you'd like**
- Check possibilities of migration to mentioned OS's. Find a way we can support them in our supported versions.
- Discuss with the team possible scenarios and choose the path how upgrade and support should be handled.

**What is the reason or source for the spike**
Just before start with tasks https://github.com/epiphany-platform/epiphany/issues/1332 and https://github.com/epiphany-platform/epiphany/issues/1331 We have to find a way how to handle the upgrades.

**Additional context**
Questions:
- Shall we support upgrade within one host?
- If so, upgrades should be done automatically or manually by the user?
- Will we support both (old & new) OS in particular Epiphany version?
- How we will treat LTS in that matter?
- What steps do we have to do in the case of modules OS images?

---

**DoD checklist**

* [x] Reader is able to understand the results of spike
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [ ] Each value / cell in the results table is described more deeply below
* [x] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by to-bar** [comment]
Related issue: #2572

**Comment by plirglo** [comment]
## Red Hat upgrade:

- _Shall we support upgrade within one host?_

Yes, we've got clients who use Epiphany 1.0 LTS and we have to guarantee them way to upgrade to newer system version within support window, whereas it is possible, supported and described in Red Hat documentation.

- _If so, upgrades should be done automatically or manually by the user?_

This should be done manually by client because this could be complex and depends on configuration used. But we should provide consistent documentation including differences between clouds, and on-prem installation

_Will we support both (old & new) OS in particular Epiphany version?_

Starting from version 2.0 LTS we should support only major version 8 to limit maintained versions and tests. But clients use version 7 (Epiphany 1.0) should be able to upgrade systems (point 1)

_How we will treat LTS in that matter?_

Manually upgraded system should be upgradeable to Epiphany v2.0

_What steps do we have to do in the case of modules OS images?_

We do not support upgrade process in modules, see @mkyc comment in task #1332

Detailed documentation created in confluence

**Comment by erzetpe** [comment]
After analysis the same approach should be applied also for Ubuntu 20.04 upgrade from 18.04.

**Comment by mkyc** [comment]
All looks good to me.
