### ISSUE TITLE
DOC: How to configure Prometheus alerts

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#631]
Document or decide if its still valid:

https://github.com/epiphany-platform/epiphany/blob/cleanup/docs/home/howto/MONITORING.md#how-to-configure-prometheus-alerts

**Comment by rafzei** [comment]
@seriva this issue is to document how to enable Prometheus alerts or how to configure Alertmanager?
Some time ago I've added few basic alerts and documented it: https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/MONITORING.md#how-to-enable-provided-prometheus-rules
not sure if this issue is still valid.

**Comment by seriva** [comment]
Looking at the history and what was added I think this is done:

![image](https://user-images.githubusercontent.com/11056665/133386964-781516a0-a8a2-409e-8074-4f39f5a57db5.png)

When I made this issue I removed some old invalid documentation and made this story to rewrite it which clearly has been done in the last 2 years:)
